INSERT INTO SONG(ID, STREAMS, OWNER) VALUES (24, 100, 'rapper');
INSERT INTO SONG(ID, STREAMS, OWNER) VALUES (25, 120, 'rapper');
INSERT INTO SONG(ID, STREAMS, OWNER) VALUES (26, 140, 'rapper');
INSERT INTO SONG(ID, STREAMS, OWNER) VALUES (27, 160, 'rapper');