INSERT INTO SONG(ID, OWNER, STREAMS) VALUES (1, 'rapper',0);
INSERT INTO SONG(ID, OWNER, STREAMS) VALUES (2, 'rapper',0);
INSERT INTO SONG(ID, OWNER, STREAMS) VALUES (3, 'rapper',0);
INSERT INTO SONG(ID, OWNER, STREAMS) VALUES (4, 'rapper',0);